import 'package:flutter/material.dart';
import 'package:book_my_seat/book_my_seat.dart';
import 'package:flutter_book_ur_tickets/pages/datetime_model.dart';
import 'package:flutter_svg/flutter_svg.dart';

class Gredient {
  static Gradient gradient1 = LinearGradient(colors: [
    const Color.fromARGB(255, 70, 70, 70),
    const Color.fromARGB(221, 0, 0, 0),
  ], begin: Alignment.topLeft, end: Alignment.bottomRight);
}

class Seatbook extends StatefulWidget {
  final String? movieHouse;
  const Seatbook({super.key, this.movieHouse});

  @override
  State<Seatbook> createState() => _SeatbookState();
}

class _SeatbookState extends State<Seatbook> {
  void showPopup(BuildContext context, int totalAmount) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Payment'),
          content: Text('Total amount to pay: Rs. ${totalAmount.toString()}'),
          actions: <Widget>[
            TextButton(
              child: Text(
                'OK',
                style: Fontfamily.whiteFont16,
              ),
              onPressed: () {
                Navigator.of(context).pop();
                showDialog(
                  context: context,
                  builder: (BuildContext context) {
                    return AlertDialog(
                      title: Text(
                        'Booking Complete',
                        style: Fontfamily.whiteFont20,
                      ),
                      icon: Icon(
                        Icons.done,
                        color: Colors.green,
                        size: 100,
                      ),
                      content: Text(
                        'Your booking is complete. Enjoy your movie!',
                        style: Fontfamily.whiteFont16,
                      ),
                      actions: [
                        TextButton(
                          child: Text(
                            'OK',
                            style: Fontfamily.whiteFont16,
                          ),
                          onPressed: () {
                            Navigator.of(context).pop();
                            Navigator.of(context).pop();
                            Navigator.of(context).pop();
                            Navigator.of(context).pop();
                            Navigator.of(context).pop();
                          },
                        ),
                      ],
                    );
                  },
                );
              },
            ),
          ],
        );
      },
    );
  }

  List<List<SeatState>> previousState =
      List.generate(22, (i) => List.generate(20, (j) => SeatState.unselected));
  int selectedSeatCount = 0;
  int neededSeatCount = 1;
  int totalamount = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.movieHouse ?? 'Default Movie House'),
      ),
      body: Container(
        alignment: Alignment.topCenter,
        child: SingleChildScrollView(
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(height: 10),
                Image.asset(
                  'assets/files/screen.png',
                  width: 390,
                ),
                SizedBox(height: 40),
                SeatLayoutWidget(
                    stateModel: SeatLayoutStateModel(
                        rows: 22,
                        cols: 20,
                        seatSvgSize: 18,
                        currentSeatsState: [
                          [
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.disabled,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.disabled,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                          ],
                          [
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                          ],
                          [
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.disabled,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.disabled,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                          ],
                          [
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                            SeatState.empty,
                          ],
                          [
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.unselected,
                            SeatState.sold,
                            SeatState.sold,
                          ],
                        ],
                        pathSelectedSeat: 'assets/files/seat_selected.svg',
                        pathDisabledSeat: 'assets/files/seat_disabled.svg',
                        pathSoldSeat: 'assets/files/seat_sold.svg',
                        pathUnSelectedSeat: 'assets/files/seat_unselected.svg'),
                    onSeatStateChanged:
                        (int rowI, int colI, SeatState currentState) {
                      setState(() {
                        if (currentState == SeatState.selected) {
                          totalamount += 200; // Assuming each seat costs 200
                          selectedSeatCount++; // Increment the selected seat count
                        } else if (currentState == SeatState.unselected) {
                          if (previousState[rowI][colI] == SeatState.selected) {
                            totalamount -= 200; // Assuming each seat costs 200
                            selectedSeatCount--; // Decrement the selected seat count
                          }
                        }
                        previousState[rowI][colI] = currentState;
                      });
                      if (selectedSeatCount >= neededSeatCount) {
                        setState(() {});
                      }
                    }),
                SizedBox(
                  height: 40,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    SvgPicture.asset(
                      'assets/files/seat_selected.svg',
                      height: 30,
                      width: 30,
                    ),
                    Text('Selected seats', style: Fontfamily.subFont12),
                    SizedBox(
                      width: 8,
                    ),
                    SvgPicture.asset(
                      'assets/files/seat_sold.svg',
                      height: 30,
                      width: 30,
                    ),
                    Text('Sold seats', style: Fontfamily.subFont12),
                    SizedBox(
                      width: 8,
                    ),
                    SvgPicture.asset(
                      'assets/files/seat_unselected.svg',
                      height: 30,
                      width: 30,
                    ),
                    Text('Unselected seats', style: Fontfamily.subFont12),
                  ],
                ),
                SizedBox(
                  height: 20,
                ),
                Row(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Padding(
                        padding: const EdgeInsets.fromLTRB(0, 0, 20, 0),
                        child: Text(
                          'Total Amount: $totalamount',
                          style: Fontfamily.subFont12,
                          textAlign: TextAlign.center,
                        ),
                      ),
                      selectedSeatCount >= neededSeatCount
                          ? GestureDetector(
                              child: Container(
                                alignment: Alignment.center,
                                width: MediaQuery.of(context).size.width - 200,
                                height: 48,
                                decoration: BoxDecoration(
                                    color: Colors.redAccent,
                                    borderRadius: BorderRadius.circular(10)),
                                child: Text(
                                  'Pay $totalamount',
                                  style: Fontfamily.whiteFont16,
                                  textAlign: TextAlign.center,
                                ),
                              ),
                              onTap: () {
                                showPopup(context, totalamount);
                              },
                            )
                          : Container()
                    ])
              ],
            ),
          ),
        ),
      ),
    );
  }
}
